default_stages:
  - commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer

  - repo: local
    hooks:
    - entry: django-upgrade --target-version 3.2
      exclude: ^$
      id: django-upgrade
      language: system
      name: django-upgrade
      pass_filenames: true
      stages:
        - commit
      types:
        - python
      types_or: []

    - entry: black
      exclude: ^$
      files: ""
      id: black
      language: system
      name: black
      pass_filenames: true
      stages:
        - commit
      types:
        - python
        - file
      types_or: []

    - entry: isort
      exclude: "^.*/js/.*$"
      files: ""
      id: isort
      language: python
      name: isort
      pass_filenames: true
      stages:
        - commit
      types:
        - python

    - entry: flake8
      exclude: ^$
      files: ""
      id: flake8
      language: python
      name: flake8
      pass_filenames: true
      stages:
        - commit
      types:
        - python
      types_or: []

    - entry: mypy
      exclude: ^$
      # note: it would be good to extend this to other apps as well
      files: "admin_dashboard/"
      id: mypy
      language: python
      name: mypy
      pass_filenames: true
      stages:
        - commit
      types:
        - python
      types_or: []
