version: '3'

services:
  django-stripe:
    env_file:
      - ../.env
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        # note: if you want to use a specific UID and GID, ensure to add it to
        #       the .env file
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${DJANGO_PORT}/health"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 40s  # requires docker-compose 3.4
    volumes:
      - ..:/opt/services/poc-django-stripe
    network_mode: host

  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: stripe-cli
    stdin_open: true
    tty: true
    privileged: true
    env_file:
      - ../.env
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    entrypoint: /bin/sh
    command: ""

  stripe-mock:
    image: stripe/stripe-mock:latest
    ports:
      - 12111-12112:12111-12112
    healthcheck:
      test: [
        "CMD", "wget", "--quiet", "--spider",
        "http://localhost:12111/v1/charges",
        "--header", "Authorization: Bearer sk_test_123"
      ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 40s  # requires docker-compose 3.4
