version: '3'

volumes:
  poc_django_stripe_local_postgres_data: {}
  poc_django_stripe_local_postgres_data_backups: {}

services:
  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: stripe-cli
    stdin_open: true
    tty: true
    env_file:
      - ../.env
    network_mode: host
    entrypoint: /bin/sh
    command: ""
