name: poc-dj-stripe
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python 3.10.*
  - psycopg2
  # dev
  - black
  - docker-compose
  - make
  - pip
  - poetry
  - pre-commit
  - black
  - flake8
  - isort
  - mypy
